name: flutter_chat
description: "This is a web chat created on Flutter and Firebase. Visitors can communicate with each other in real time, as well as share their posts with other participants. The chat has a simple and intuitive interface, and it also has all the features of a modern chat, including sending emoticons and images."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.9.0
  provider: ^6.1.2
  convex_bottom_bar: 3.2.0
  firebase_auth: ^5.3.4
  awesome_dialog: 3.2.1
  cloud_firestore: ^5.6.0
  modal_bottom_sheet: 3.0.0
  date_format: 2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets: 
   - assets/images/
